### ISSUE TITLE
db error when adding show

### ISSUE THREAD

**Issue by MartinAyla** [Pistachitos/Sick-Beard#24]
I'm trying to add "Fringe" but I get the error below.

Any way to repair my db, or other ideas?

Thanks
Martin

---

AAOperationalError: near "WHERE": syntax error
AA    sqlResult = self.connection.execute(query, args)
AA  File "/Applications/Sick-Beard/sickbeard/db.py", line 74, in action
AA    self.action(query, valueDict.values() + keyDict.values())
AA  File "/Applications/Sick-Beard/sickbeard/db.py", line 110, in upsert
AA    myDB.upsert("imdb_info", newValueDict, controlValueDict)
AA  File "/Applications/Sick-Beard/sickbeard/tv.py", line 982, in saveToDB
AA    self.saveToDB()
AA  File "/Applications/Sick-Beard/sickbeard/tv.py", line 94, in **init**
AA    newShow = TVShow(self.tvdb_id, self.lang)
AA  File "/Applications/Sick-Beard/sickbeard/show_queue.py", line 262, in execute
Apr-06 16:57:16 DEBUG    SHOWQUEUE-ADD :: Traceback (most recent call last):
Apr-06 16:57:16 ERROR    SHOWQUEUE-ADD :: Error trying to add show: near "WHERE": syntax error
Apr-06 16:57:16 ERROR    SHOWQUEUE-ADD :: DB error: near "WHERE": syntax error
Apr-06 16:57:16 DB       SHOWQUEUE-ADD :: sickbeard.db: UPDATE imdb_info SET  WHERE tvdb_id = ? with args [82066]
Apr-06 16:57:16 DB       SHOWQUEUE-ADD :: sickbeard.db: UPDATE tv_shows SET status = ?, air_by_date = ?, flatten_folders = ?, network = ?, startyear = ?, show_name = ?, tvr_name = ?, paused = ?, airs = ?, location = ?, imdb_id = ?, genre = ?, runtime = ?, quality = ?, tvr_id = ?, subtitles = ?, lang = ? WHERE tvdb_id = ? with args [u'Ended', 0, 0, u'FOX', 2008, u'Fringe', u'Fringe', 0, u'Friday 9:00 PM', u'/Volumes/Promise/TV Shows/Fringe', u'tt1119644', u'|Drama|Science-Fiction|', 60, 10485924, 18388, 1, u'en', 82066]
Apr-06 16:57:16 DEBUG    SHOWQUEUE-ADD :: 82066: Saving show info to database
Apr-06 16:57:16 INFO     SHOWQUEUE-ADD :: 82066: Unable to find IMDb show info in the database
Apr-06 16:57:16 DB       SHOWQUEUE-ADD :: sickbeard.db: SELECT \* FROM imdb_info WHERE tvdb_id = ? with args [82066]
Apr-06 16:57:16 DB       SHOWQUEUE-ADD :: sickbeard.db: SELECT \* FROM tv_shows WHERE tvdb_id = ? with args [82066]
Apr-06 16:57:16 INFO     SHOWQUEUE-ADD :: 82066: Loading show info from database
Apr-06 16:57:16 DB       SHOWQUEUE-ADD :: cache.db: DELETE FROM scene_names WHERE tvdb_id = ? with args [0]
Apr-06 16:57:15 INFO     SHOWQUEUE-ADD :: TVDB: {'useZip': True, 'apikey': '9DAF49C96CBF8DAC', 'cache': '/Applications/Sick-Beard/cache/tvdb', 'language': u'en'}
Apr-06 16:57:15 INFO     SHOWQUEUE-ADD :: Starting to add show /Volumes/Promise/TV Shows/Fringe

**Comment by isetz** [comment]
Ok this happens because the show has and imdb_id defined but information doesn't exist in imdb_info table for that ID. I'm not able to reproduce the error, it should have filled both tv_shows and imdb_info tables correctly.

If you still have this problem and the show is broken you should delete the imdb_id attribute value from tv_shows table for Fringe. 

To do that I reccomend you to stop SickBeard, then download SQLite Manager extension for Firefox (well, feel free to use any management solution if you have another one) and open sickbeard.db file with it (located at SB root folder). Then select tv_shows table on the left panel and use the Search button on your right to find the entry for Fringe (filter by show_name for example). After you have found the entry for Fringe in tv_shows just click the Edit button, search for the last attribute of the list imdb_id, delete its value and click OK to save your changes. After that start SB and you should be able to enter and see the show details.

To update the show and get the IMDB info you can force a full update.

Reopen the ticket if you can't solve the problem.
